version: "3.8"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    depends_on:
      - elasticmq

  elasticmq:
    image: softwaremill/elasticmq-native
    ports:
      - "9324:9324"
    environment:
      - JAVA_OPTS=-Delasticmq.rest.port=9324
      - CONFIG_FILE=/opt/elasticmq.conf
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://elasticmq:9324" ]
      interval: 5s
      retries: 5
      start_period: 5s