version: "3.8"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    depends_on:
      - elasticmq

  elasticmq:
    image: softwaremill/elasticmq-native
    ports:
      - "9324:9324"  # SQS endpoint
      - "9325:9325"  # Web UI
    environment:
      - JAVA_OPTS=-Delasticmq.rest.port=9324
      - CONFIG_FILE=/opt/elasticmq.conf
      - ELASTICMQ_UI=true
      - JAVA_OPTS=-Dconfig.file=/opt/elasticmq.conf